name: Run E2E Tests
on: [pull_request]
jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      api-solid-pg:
        image: bitnami/postgresql:latest
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid

    steps:
      - uses: actions/checkout@v3
      - name: Install NodeJS # Sometimes we don't need this step if the runner already has it installed
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm' # github will create a cache of dependencies
      - name: Install dependencies
        run: npm ci # installing a clean install of devDependencies
      - name: Run tests
        run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"